<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Packet.Tait.Codeplug</RootNamespace>
    <AssemblyName>tait-codeplug</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Packet.Tait.Codeplug\Packet.Tait.Codeplug.csproj" />
  </ItemGroup>

</Project>
