// Code generated by tools/Packet.Sdl.CodeGen from
// spec-sdl/data-link/subroutines.sdl.yaml. DO NOT EDIT. Run `dotnet run
// --project tools/Packet.Sdl.CodeGen` to regenerate.

#include "ax25sdl.h"

static const ActionStep
    data_link_subroutines_n_r_error_recovery_t01_recover_actions[] = {
        {.verb = "DL-ERROR Indication (J)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Clear Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_clear_exception_conditions_t01_clear_all_actions[] = {
        {.verb = "Clear Peer Receiver Busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Own Receiver Busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Reject Condition", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Sreject Condition", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Discard I Queue Entries", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_transmit_enquiry_t01_not_busy_sends_rr_actions[] = {
        {.verb = "P <- 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N(r) <- V(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RR Command", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_transmit_enquiry_t02_busy_sends_rnr_actions[] = {
        {.verb = "P <- 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N(r) <- V(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RNR Command", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_enquiry_response_t01_not_polled_rr_response_actions
        [] = {
            {.verb = "N(r) <- V(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "RR Response", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Clear Acknowledge Pending",
             .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_enquiry_response_t02_polled_busy_rnr_actions[] = {
        {.verb = "N(r) <- V(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RNR Response", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_enquiry_response_t03_polled_srej_disabled_rr_actions
        [] = {
            {.verb = "N(r) <- V(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "RR Response", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Clear Acknowledge Pending",
             .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_enquiry_response_t04_polled_srej_mod8_dl_error_then_buf_yes_actions
        [] = {
            {.verb = "N(r) <- V(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "DL-ERROR Indication (add)",
             .kind = AX25SDL_KIND_SIGNAL_UPPER},
            {.verb = "SREJ", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "RR Response", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Clear Acknowledge Pending",
             .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_enquiry_response_t05_polled_srej_mod8_dl_error_then_buf_no_actions
        [] = {
            {.verb = "N(r) <- V(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "DL-ERROR Indication (add)",
             .kind = AX25SDL_KIND_SIGNAL_UPPER},
            {.verb = "RR Response", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Clear Acknowledge Pending",
             .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_enquiry_response_t06_polled_srej_mod128_buf_yes_actions
        [] = {
            {.verb = "N(r) <- V(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "SREJ", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "RR Response", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Clear Acknowledge Pending",
             .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_enquiry_response_t07_polled_srej_mod128_buf_no_actions
        [] = {
            {.verb = "N(r) <- V(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "RR Response", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Clear Acknowledge Pending",
             .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_invoke_retransmission_t01_retransmit_loop_actions[] =
        {
            {.verb = "Backtrack", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "X <- V(s)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "V(s) <- N(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Push Old I Frame onto Queue",
             .kind = AX25SDL_KIND_INTERNAL_OUT},
            {.verb = "V(s) <- V(s) + 1", .kind = AX25SDL_KIND_PROCESSING},
};

static const LoopRange
    data_link_subroutines_invoke_retransmission_t01_retransmit_loop_loops[] = {
        {.start = 3, .length = 2, .predicate = "not v_s_eq_x"},
};

static const ActionStep
    data_link_subroutines_check_i_frame_acknowledged_t01_peer_busy_t1_running_actions
        [] = {
            {.verb = "V(a) <- N(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_check_i_frame_acknowledged_t02_peer_busy_t1_stopped_actions
        [] = {
            {.verb = "V(a) <- N(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_check_i_frame_acknowledged_t03_caught_up_select_t1_actions
        [] = {
            {.verb = "V(a) <- N(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Stop T1", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Start T3", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Select_T1_Value", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep
    data_link_subroutines_check_i_frame_acknowledged_t05_partial_ack_progress_actions
        [] = {
            {.verb = "V(a) <- N(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_establish_data_link_t01_mod_8_sabm_actions[] = {
        {.verb = "Clear Exception Conditions", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RC <- 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "P <- 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "SABM", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_establish_data_link_t02_mod_128_sabme_actions[] = {
        {.verb = "Clear Exception Conditions", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RC <- 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "P <- 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "SABME", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_establish_extended_data_link_t01_mod_8_sabm_actions
        [] = {
            {.verb = "Clear Exception Conditions",
             .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "RC <- 1", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "P <- 1", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "SABM", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_establish_extended_data_link_t02_mod_128_sabme_actions
        [] = {
            {.verb = "Clear Exception Conditions",
             .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "RC <- 1", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "P <- 1", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "SABME", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_check_need_for_response_t01_command_poll_enquiry_response_actions
        [] = {
            {.verb = "Enquiry_Response_F_1", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep
    data_link_subroutines_check_need_for_response_t02_response_f_unexpected_dl_error_actions
        [] = {
            {.verb = "DL-ERROR Indication (A)",
             .kind = AX25SDL_KIND_SIGNAL_UPPER},
};

static const ActionStep
    data_link_subroutines_u_i_check_t01_response_dl_error_q_actions[] = {
        {.verb = "DL-ERROR Indication (Q)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
};

static const ActionStep
    data_link_subroutines_u_i_check_t02_command_valid_unit_data_actions[] = {
        {.verb = "DL-UNIT-DATA Indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
};

static const ActionStep
    data_link_subroutines_u_i_check_t03_command_invalid_dl_error_k_actions[] = {
        {.verb = "DL-ERROR Indication (K)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
};

static const ActionStep
    data_link_subroutines_select_t1_value_t01_fresh_ack_iir_actions[] = {
        {.verb = "SRT <- 7(SRT)/8 + (T1)/8 - (Remaining Time on T1 When Last "
                 "Stopped)/8",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Next T1 <- 2 * SRT", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_select_t1_value_t02_retry_t1_expired_actions[] = {
        {.verb = "Next T1 <- (RC*0.25)+SRT*2", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_set_version_2_0_t01_v2_0_defaults_actions[] = {
        {.verb = "Set Half Duplex", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Set Implicit Reject", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Modulo <- 8", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N1 <- 2048", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "k <- 8", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "T2 <- 3000", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N2 <- 10", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_subroutines_set_version_2_2_t01_v2_2_defaults_actions[] = {
        {.verb = "Set Half Duplex", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Set Selective Reject", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Modulo <- 128", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N1 <- 2048", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "k <- 32", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "T2 <- 3000", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N2 <- 10", .kind = AX25SDL_KIND_PROCESSING},
};

static const SubroutinePath data_link_subroutines_n_r_error_recovery_paths[] = {
    {
        .id = "t01_recover",
        .guard = "",
        .actions = data_link_subroutines_n_r_error_recovery_t01_recover_actions,
        .actions_len = 3,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutinePath
    data_link_subroutines_clear_exception_conditions_paths[] = {
        {
            .id = "t01_clear_all",
            .guard = "",
            .actions =
                data_link_subroutines_clear_exception_conditions_t01_clear_all_actions,
            .actions_len = 6,
            .notes = "",
            .references = NULL,
            .references_len = 0,
            .loops = NULL,
            .loops_len = 0,
        },
};

static const SubroutinePath data_link_subroutines_transmit_enquiry_paths[] = {
    {
        .id = "t01_not_busy_sends_rr",
        .guard = "not own_receiver_busy",
        .actions =
            data_link_subroutines_transmit_enquiry_t01_not_busy_sends_rr_actions,
        .actions_len = 5,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t02_busy_sends_rnr",
        .guard = "own_receiver_busy",
        .actions =
            data_link_subroutines_transmit_enquiry_t02_busy_sends_rnr_actions,
        .actions_len = 5,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutinePath data_link_subroutines_enquiry_response_paths[] = {
    {
        .id = "t01_not_polled_rr_response",
        .guard = "not f_eq_1_and_supervisory_or_i",
        .actions =
            data_link_subroutines_enquiry_response_t01_not_polled_rr_response_actions,
        .actions_len = 3,
        .notes = "F==1-supervisory-or-I check fails; just send RR Response.\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t02_polled_busy_rnr",
        .guard = "f_eq_1_and_supervisory_or_i and own_receiver_busy",
        .actions =
            data_link_subroutines_enquiry_response_t02_polled_busy_rnr_actions,
        .actions_len = 3,
        .notes = "Polled and we're busy: respond with RNR.\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_polled_srej_disabled_rr",
        .guard = "f_eq_1_and_supervisory_or_i and not own_receiver_busy and "
                 "not srej_enabled",
        .actions =
            data_link_subroutines_enquiry_response_t03_polled_srej_disabled_rr_actions,
        .actions_len = 3,
        .notes =
            "Polled, not busy, SREJ not enabled → just RR Response.\n(Added in "
            "commit 46d3782 after the original redraw omitted\nthis edge.)\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t04_polled_srej_mod8_dl_error_then_buf_yes",
        .guard = "f_eq_1_and_supervisory_or_i and not own_receiver_busy and "
                 "srej_enabled and mod_8 and "
                 "out_of_sequence_frames_in_receive_buffer",
        .actions =
            data_link_subroutines_enquiry_response_t04_polled_srej_mod8_dl_error_then_buf_yes_actions,
        .actions_len = 5,
        .notes = "Polled, not busy, SREJ enabled, Mod 8 (so DL-ERROR "
                 "add),\nand we have stored out-of-sequence frames → emit "
                 "SREJ\nbefore the RR Response.\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t05_polled_srej_mod8_dl_error_then_buf_no",
        .guard = "f_eq_1_and_supervisory_or_i and not own_receiver_busy and "
                 "srej_enabled and mod_8 and not "
                 "out_of_sequence_frames_in_receive_buffer",
        .actions =
            data_link_subroutines_enquiry_response_t05_polled_srej_mod8_dl_error_then_buf_no_actions,
        .actions_len = 4,
        .notes = "Same as t04 but no stored out-of-sequence frames → "
                 "straight\nto RR Response after DL-ERROR.\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t06_polled_srej_mod128_buf_yes",
        .guard = "f_eq_1_and_supervisory_or_i and not own_receiver_busy and "
                 "srej_enabled and not mod_8 and "
                 "out_of_sequence_frames_in_receive_buffer",
        .actions =
            data_link_subroutines_enquiry_response_t06_polled_srej_mod128_buf_yes_actions,
        .actions_len = 4,
        .notes = "Polled, not busy, SREJ enabled, Mod 128 (no DL-ERROR), "
                 "and\nstored frames present → SREJ then RR Response.\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t07_polled_srej_mod128_buf_no",
        .guard = "f_eq_1_and_supervisory_or_i and not own_receiver_busy and "
                 "srej_enabled and not mod_8 and not "
                 "out_of_sequence_frames_in_receive_buffer",
        .actions =
            data_link_subroutines_enquiry_response_t07_polled_srej_mod128_buf_no_actions,
        .actions_len = 3,
        .notes = "Polled, not busy, SREJ enabled, Mod 128, no stored frames "
                 "→\nstraight to RR Response.\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutinePath data_link_subroutines_invoke_retransmission_paths[] = {
    {
        .id = "t01_retransmit_loop",
        .guard = "",
        .actions =
            data_link_subroutines_invoke_retransmission_t01_retransmit_loop_actions,
        .actions_len = 5,
        .notes = "The figure draws this as a diamond loop `Push... → V(s) := "
                 "V(s)+1 → V(s) == X? → if No, back to Push`. Our `loop_while` "
                 "construct iterates while its predicate is TRUE, so we encode "
                 "the inverse `v_s_neq_x` (predicate `not v_s_eq_x`). A future "
                 "codegen extension could accept a `negate: true` modifier so "
                 "the YAML can reuse the figure's literal predicate; for now "
                 "we encode the inverse.\n",
        .references = NULL,
        .references_len = 0,
        .loops =
            data_link_subroutines_invoke_retransmission_t01_retransmit_loop_loops,
        .loops_len = 1,
    },
};

static const SubroutinePath data_link_subroutines_check_i_frame_acknowledged_paths[] = {
    {
        .id = "t01_peer_busy_t1_running",
        .guard = "peer_receiver_busy and t1_running",
        .actions =
            data_link_subroutines_check_i_frame_acknowledged_t01_peer_busy_t1_running_actions,
        .actions_len = 2,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t02_peer_busy_t1_stopped",
        .guard = "peer_receiver_busy and not t1_running",
        .actions =
            data_link_subroutines_check_i_frame_acknowledged_t02_peer_busy_t1_stopped_actions,
        .actions_len = 3,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_caught_up_select_t1",
        .guard = "not peer_receiver_busy and n_r_eq_v_s",
        .actions =
            data_link_subroutines_check_i_frame_acknowledged_t03_caught_up_select_t1_actions,
        .actions_len = 4,
        .notes = "Peer not busy, N(r) == V(s): we're fully caught up. "
                 "Update\nV(a), stop T1, start T3, then run Select_T1_Value "
                 "to\nrecompute the next T1.\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t04_partial_ack_n_r_eq_v_a",
        .guard = "not peer_receiver_busy and not n_r_eq_v_s and n_r_eq_v_a",
        .actions = NULL,
        .actions_len = 0,
        .notes = "Peer not busy, N(r) != V(s) but N(r) == V(a): no "
                 "progress;\ndrop straight to the join (no action).\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t05_partial_ack_progress",
        .guard = "not peer_receiver_busy and not n_r_eq_v_s and not n_r_eq_v_a",
        .actions =
            data_link_subroutines_check_i_frame_acknowledged_t05_partial_ack_progress_actions,
        .actions_len = 2,
        .notes = "Peer not busy, partial ack with progress: advance V(a) "
                 "and\nrestart T1.\n",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutinePath data_link_subroutines_establish_data_link_paths[] = {
    {
        .id = "t01_mod_8_sabm",
        .guard = "not mod_128",
        .actions =
            data_link_subroutines_establish_data_link_t01_mod_8_sabm_actions,
        .actions_len = 6,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t02_mod_128_sabme",
        .guard = "mod_128",
        .actions =
            data_link_subroutines_establish_data_link_t02_mod_128_sabme_actions,
        .actions_len = 6,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutinePath
    data_link_subroutines_establish_extended_data_link_paths[] = {
        {
            .id = "t01_mod_8_sabm",
            .guard = "not mod_128",
            .actions =
                data_link_subroutines_establish_extended_data_link_t01_mod_8_sabm_actions,
            .actions_len = 6,
            .notes = "",
            .references = NULL,
            .references_len = 0,
            .loops = NULL,
            .loops_len = 0,
        },
        {
            .id = "t02_mod_128_sabme",
            .guard = "mod_128",
            .actions =
                data_link_subroutines_establish_extended_data_link_t02_mod_128_sabme_actions,
            .actions_len = 6,
            .notes = "",
            .references = NULL,
            .references_len = 0,
            .loops = NULL,
            .loops_len = 0,
        },
};

static const SubroutinePath data_link_subroutines_check_need_for_response_paths[] = {
    {
        .id = "t01_command_poll_enquiry_response",
        .guard = "command_and_p_eq_1",
        .actions =
            data_link_subroutines_check_need_for_response_t01_command_poll_enquiry_response_actions,
        .actions_len = 1,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t02_response_f_unexpected_dl_error",
        .guard = "not command_and_p_eq_1 and response_and_f_eq_1",
        .actions =
            data_link_subroutines_check_need_for_response_t02_response_f_unexpected_dl_error_actions,
        .actions_len = 1,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_neither_silent_return",
        .guard = "not command_and_p_eq_1 and not response_and_f_eq_1",
        .actions = NULL,
        .actions_len = 0,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutinePath data_link_subroutines_u_i_check_paths[] = {
    {
        .id = "t01_response_dl_error_q",
        .guard = "not incoming_is_command",
        .actions =
            data_link_subroutines_u_i_check_t01_response_dl_error_q_actions,
        .actions_len = 1,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t02_command_valid_unit_data",
        .guard = "incoming_is_command and ui_info_field_valid",
        .actions =
            data_link_subroutines_u_i_check_t02_command_valid_unit_data_actions,
        .actions_len = 1,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_command_invalid_dl_error_k",
        .guard = "incoming_is_command and not ui_info_field_valid",
        .actions =
            data_link_subroutines_u_i_check_t03_command_invalid_dl_error_k_actions,
        .actions_len = 1,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutinePath data_link_subroutines_select_t1_value_paths[] = {
    {
        .id = "t01_fresh_ack_iir",
        .guard = "rc_eq_0",
        .actions =
            data_link_subroutines_select_t1_value_t01_fresh_ack_iir_actions,
        .actions_len = 2,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t02_retry_t1_expired",
        .guard = "not rc_eq_0 and t1_expired",
        .actions =
            data_link_subroutines_select_t1_value_t02_retry_t1_expired_actions,
        .actions_len = 1,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_no_change",
        .guard = "not rc_eq_0 and not t1_expired",
        .actions = NULL,
        .actions_len = 0,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutinePath data_link_subroutines_set_version_2_0_paths[] = {
    {
        .id = "t01_v2_0_defaults",
        .guard = "",
        .actions =
            data_link_subroutines_set_version_2_0_t01_v2_0_defaults_actions,
        .actions_len = 7,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutinePath data_link_subroutines_set_version_2_2_paths[] = {
    {
        .id = "t01_v2_2_defaults",
        .guard = "",
        .actions =
            data_link_subroutines_set_version_2_2_t01_v2_2_defaults_actions,
        .actions_len = 7,
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

static const SubroutineSpec data_link_subroutines_subroutines[] = {
    {
        .name = "N_r_Error_Recovery",
        .paths = data_link_subroutines_n_r_error_recovery_paths,
        .paths_len = 1,
        .notes = "Three-step recovery when an inbound frame's N(r) is "
                 "invalid.\nSignals DL-ERROR (J), calls Establish_Data_Link to "
                 "restart the\nlink, then clears the Layer-3-initiated flag.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Clear_Exception_Conditions",
        .paths = data_link_subroutines_clear_exception_conditions_paths,
        .paths_len = 1,
        .notes =
            "Six-action reset of all exception bookkeeping. Drawn as a "
            "single\nmulti-line processing box in the figure; transcribed as "
            "one\naction per line per the runbook's multi-line-box rule.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Transmit_Enquiry",
        .paths = data_link_subroutines_transmit_enquiry_paths,
        .paths_len = 2,
        .notes = "Polls the peer with RR-cmd or RNR-cmd (P=1) depending on "
                 "whether\nwe ourselves are in busy state.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Enquiry_Response",
        .paths = data_link_subroutines_enquiry_response_paths,
        .paths_len = 7,
        .notes = "Polled-response handler. Five chained decisions; multiple "
                 "paths\nconverge on a shared \"RR Response\" + \"Clear "
                 "Acknowledge Pending\"\ntail before return.\n\nBoth figure "
                 "ambiguities flagged on the original transcription\n(commit "
                 "caa7326) were resolved upstream in commit 46d3782:\nn22 "
                 "SREJ-Enabled?=No now explicitly routes to RR Response.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Invoke_Retransmission",
        .paths = data_link_subroutines_invoke_retransmission_paths,
        .paths_len = 1,
        .notes =
            "Push every I-frame from N(r) up to V(s) back onto the "
            "send\nqueue. Spec-canonical loop: backtrack V(s) to N(r), "
            "push,\nincrement, repeat until back at X (the original V(s)).\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Check_I_Frame_Acknowledged",
        .paths = data_link_subroutines_check_i_frame_acknowledged_paths,
        .paths_len = 5,
        .notes = "Process an incoming N(r) and update V(a) / T1 / T3 "
                 "state\naccordingly. Four chained decisions, multiple join "
                 "paths.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Establish_Data_Link",
        .paths = data_link_subroutines_establish_data_link_paths,
        .paths_len = 2,
        .notes = "Clear exception bookkeeping, set the retry counter and P "
                 "flag,\nsend SABM or SABME depending on Mod 128 state, then "
                 "start T1.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Establish_Extended_Data_Link",
        .paths = data_link_subroutines_establish_extended_data_link_paths,
        .paths_len = 2,
        .notes =
            "Shares its body with Establish_Data_Link (both "
            "subroutine-start\nnodes in the graphml flow into the same shared "
            "body at n48).\nFunctionally identical — the body's `Mod 128?` "
            "test picks\nSABM vs SABME so the caller's choice of name is "
            "informational.\nTracked separately because state-machine pages "
            "(figc4.2 vs\nfigc4.4) reference them by distinct names.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Check_Need_For_Response",
        .paths = data_link_subroutines_check_need_for_response_paths,
        .paths_len = 3,
        .notes = "Looks at incoming command/response role + P/F bit and "
                 "either\nsends Enquiry_Response(F=1) (when it was a poll), "
                 "surfaces a\nDL-ERROR (A) (response with F=1 when not "
                 "expected), or returns\nsilently.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "UI_Check",
        .paths = data_link_subroutines_u_i_check_paths,
        .paths_len = 3,
        .notes = "Validates a received UI frame. Rejects if it's a response "
                 "(Q\nerror), accepts if info length ≤ N1 and the content "
                 "is\noctet-aligned (DL-UNIT-DATA indication), or surfaces a K "
                 "error.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Select_T1_Value",
        .paths = data_link_subroutines_select_t1_value_paths,
        .paths_len = 3,
        .notes = "Recompute SRT (smoothed round-trip estimate) and the next "
                 "T1\ntimeout. On a fresh-ack path (RC==0) the spec's "
                 "IIR-style\nformula runs; on a retry path (RC > 0, T1 "
                 "expired) we just\nbump T1V to next-attempt. Otherwise return "
                 "without change.\n\nCanonical name `Select_T1_Value` (the "
                 "figure's start label is\njust \"Select T1\" but the existing "
                 "registry / state pages use\nthe longer form).\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Set_Version_2_0",
        .paths = data_link_subroutines_set_version_2_0_paths,
        .paths_len = 1,
        .notes = "Configure all v2.0-specific parameters. Single "
                 "multi-line\nprocessing box in the figure; transcribed as one "
                 "action per\nline.\n",
        .references = NULL,
        .references_len = 0,
    },
    {
        .name = "Set_Version_2_2",
        .paths = data_link_subroutines_set_version_2_2_paths,
        .paths_len = 1,
        .notes = "Configure all v2.2-specific parameters. Differs from v2.0 "
                 "in\nSelective Reject (vs Implicit Reject), Modulo 128 (vs 8) "
                 "and\nk = 32 (vs 8).\n",
        .references = NULL,
        .references_len = 0,
    },
};

const SubroutinesPage data_link_subroutines = {
    .machine = "data_link",
    .source = {.spec = "AX.25 v2.2 rev 4",
               .figure = "C4.7",
               .url = "https://github.com/packethacking/ax25spec/blob/main/doc/"
                      "ax.25.2.2.4_Oct_25.md"},
    .subroutines = data_link_subroutines_subroutines,
    .subroutines_len = 13,
};
