// Code generated by tools/Packet.Sdl.CodeGen from spec-sdl/data-link/subroutines.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project tools/Packet.Sdl.CodeGen` to regenerate.

import type { SubroutinesPage } from "./types.js";

/**
 * SDL subroutines for the data_link machine.
 * Source: AX.25 v2.2 rev 4, figure C4.7.
 */
export const DataLinkSubroutines: SubroutinesPage = {
  machine: "data_link",
  source: { spec: "AX.25 v2.2 rev 4", figure: "C4.7", url: "https://github.com/packethacking/ax25spec/blob/main/doc/ax.25.2.2.4_Oct_25.md" },
  subroutines: [
    {
      name: "N_r_Error_Recovery",
      paths: [
        {
          id: "t01_recover",
          guard: "",
          actions: [
            { verb: "DL-ERROR Indication (J)", kind: "signal_upper" },
            { verb: "Establish_Data_Link", kind: "subroutine" },
            { verb: "Clear Layer 3 Initiated", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Three-step recovery when an inbound frame's N(r) is invalid.\nSignals DL-ERROR (J), calls Establish_Data_Link to restart the\nlink, then clears the Layer-3-initiated flag.\n",
      references: [],
    },
    {
      name: "Clear_Exception_Conditions",
      paths: [
        {
          id: "t01_clear_all",
          guard: "",
          actions: [
            { verb: "Clear Peer Receiver Busy", kind: "processing" },
            { verb: "Clear Own Receiver Busy", kind: "processing" },
            { verb: "Clear Reject Condition", kind: "processing" },
            { verb: "Clear Sreject Condition", kind: "processing" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
            { verb: "Discard I Queue Entries", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Six-action reset of all exception bookkeeping. Drawn as a single\nmulti-line processing box in the figure; transcribed as one\naction per line per the runbook's multi-line-box rule.\n",
      references: [],
    },
    {
      name: "Transmit_Enquiry",
      paths: [
        {
          id: "t01_not_busy_sends_rr",
          guard: "not own_receiver_busy",
          actions: [
            { verb: "P <- 1", kind: "processing" },
            { verb: "N(r) <- V(r)", kind: "processing" },
            { verb: "RR Command", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_busy_sends_rnr",
          guard: "own_receiver_busy",
          actions: [
            { verb: "P <- 1", kind: "processing" },
            { verb: "N(r) <- V(r)", kind: "processing" },
            { verb: "RNR Command", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Polls the peer with RR-cmd or RNR-cmd (P=1) depending on whether\nwe ourselves are in busy state.\n",
      references: [],
    },
    {
      name: "Enquiry_Response",
      paths: [
        {
          id: "t01_not_polled_rr_response",
          guard: "not f_eq_1_and_supervisory_or_i",
          actions: [
            { verb: "N(r) <- V(r)", kind: "processing" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "F==1-supervisory-or-I check fails; just send RR Response.\n",
          references: [],
          loops: [],
        },
        {
          id: "t02_polled_busy_rnr",
          guard: "f_eq_1_and_supervisory_or_i and own_receiver_busy",
          actions: [
            { verb: "N(r) <- V(r)", kind: "processing" },
            { verb: "RNR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "Polled and we're busy: respond with RNR.\n",
          references: [],
          loops: [],
        },
        {
          id: "t03_polled_srej_disabled_rr",
          guard: "f_eq_1_and_supervisory_or_i and not own_receiver_busy and not srej_enabled",
          actions: [
            { verb: "N(r) <- V(r)", kind: "processing" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "Polled, not busy, SREJ not enabled → just RR Response.\n(Added in commit 46d3782 after the original redraw omitted\nthis edge.)\n",
          references: [],
          loops: [],
        },
        {
          id: "t04_polled_srej_mod8_dl_error_then_buf_yes",
          guard: "f_eq_1_and_supervisory_or_i and not own_receiver_busy and srej_enabled and mod_8 and out_of_sequence_frames_in_receive_buffer",
          actions: [
            { verb: "N(r) <- V(r)", kind: "processing" },
            { verb: "DL-ERROR Indication (add)", kind: "signal_upper" },
            { verb: "SREJ", kind: "signal_lower" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "Polled, not busy, SREJ enabled, Mod 8 (so DL-ERROR add),\nand we have stored out-of-sequence frames → emit SREJ\nbefore the RR Response.\n",
          references: [],
          loops: [],
        },
        {
          id: "t05_polled_srej_mod8_dl_error_then_buf_no",
          guard: "f_eq_1_and_supervisory_or_i and not own_receiver_busy and srej_enabled and mod_8 and not out_of_sequence_frames_in_receive_buffer",
          actions: [
            { verb: "N(r) <- V(r)", kind: "processing" },
            { verb: "DL-ERROR Indication (add)", kind: "signal_upper" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "Same as t04 but no stored out-of-sequence frames → straight\nto RR Response after DL-ERROR.\n",
          references: [],
          loops: [],
        },
        {
          id: "t06_polled_srej_mod128_buf_yes",
          guard: "f_eq_1_and_supervisory_or_i and not own_receiver_busy and srej_enabled and not mod_8 and out_of_sequence_frames_in_receive_buffer",
          actions: [
            { verb: "N(r) <- V(r)", kind: "processing" },
            { verb: "SREJ", kind: "signal_lower" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "Polled, not busy, SREJ enabled, Mod 128 (no DL-ERROR), and\nstored frames present → SREJ then RR Response.\n",
          references: [],
          loops: [],
        },
        {
          id: "t07_polled_srej_mod128_buf_no",
          guard: "f_eq_1_and_supervisory_or_i and not own_receiver_busy and srej_enabled and not mod_8 and not out_of_sequence_frames_in_receive_buffer",
          actions: [
            { verb: "N(r) <- V(r)", kind: "processing" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "Polled, not busy, SREJ enabled, Mod 128, no stored frames →\nstraight to RR Response.\n",
          references: [],
          loops: [],
        },
      ],
      notes: "Polled-response handler. Five chained decisions; multiple paths\nconverge on a shared \"RR Response\" + \"Clear Acknowledge Pending\"\ntail before return.\n\nBoth figure ambiguities flagged on the original transcription\n(commit caa7326) were resolved upstream in commit 46d3782:\nn22 SREJ-Enabled?=No now explicitly routes to RR Response.\n",
      references: [],
    },
    {
      name: "Invoke_Retransmission",
      paths: [
        {
          id: "t01_retransmit_loop",
          guard: "",
          actions: [
            { verb: "Backtrack", kind: "processing" },
            { verb: "X <- V(s)", kind: "processing" },
            { verb: "V(s) <- N(r)", kind: "processing" },
            { verb: "Push Old I Frame onto Queue", kind: "internal_out" },
            { verb: "V(s) <- V(s) + 1", kind: "processing" },
          ],
          notes: "The figure draws this as a diamond loop `Push... → V(s) := V(s)+1 → V(s) == X? → if No, back to Push`. Our `loop_while` construct iterates while its predicate is TRUE, so we encode the inverse `v_s_neq_x` (predicate `not v_s_eq_x`). A future codegen extension could accept a `negate: true` modifier so the YAML can reuse the figure's literal predicate; for now we encode the inverse.\n",
          references: [],
          loops: [
            { start: 3, length: 2, predicate: "not v_s_eq_x" },
          ],
        },
      ],
      notes: "Push every I-frame from N(r) up to V(s) back onto the send\nqueue. Spec-canonical loop: backtrack V(s) to N(r), push,\nincrement, repeat until back at X (the original V(s)).\n",
      references: [],
    },
    {
      name: "Check_I_Frame_Acknowledged",
      paths: [
        {
          id: "t01_peer_busy_t1_running",
          guard: "peer_receiver_busy and t1_running",
          actions: [
            { verb: "V(a) <- N(r)", kind: "processing" },
            { verb: "Stop T3", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_peer_busy_t1_stopped",
          guard: "peer_receiver_busy and not t1_running",
          actions: [
            { verb: "V(a) <- N(r)", kind: "processing" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t03_caught_up_select_t1",
          guard: "not peer_receiver_busy and n_r_eq_v_s",
          actions: [
            { verb: "V(a) <- N(r)", kind: "processing" },
            { verb: "Stop T1", kind: "processing" },
            { verb: "Start T3", kind: "processing" },
            { verb: "Select_T1_Value", kind: "subroutine" },
          ],
          notes: "Peer not busy, N(r) == V(s): we're fully caught up. Update\nV(a), stop T1, start T3, then run Select_T1_Value to\nrecompute the next T1.\n",
          references: [],
          loops: [],
        },
        {
          id: "t04_partial_ack_n_r_eq_v_a",
          guard: "not peer_receiver_busy and not n_r_eq_v_s and n_r_eq_v_a",
          actions: [],
          notes: "Peer not busy, N(r) != V(s) but N(r) == V(a): no progress;\ndrop straight to the join (no action).\n",
          references: [],
          loops: [],
        },
        {
          id: "t05_partial_ack_progress",
          guard: "not peer_receiver_busy and not n_r_eq_v_s and not n_r_eq_v_a",
          actions: [
            { verb: "V(a) <- N(r)", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "Peer not busy, partial ack with progress: advance V(a) and\nrestart T1.\n",
          references: [],
          loops: [],
        },
      ],
      notes: "Process an incoming N(r) and update V(a) / T1 / T3 state\naccordingly. Four chained decisions, multiple join paths.\n",
      references: [],
    },
    {
      name: "Establish_Data_Link",
      paths: [
        {
          id: "t01_mod_8_sabm",
          guard: "not mod_128",
          actions: [
            { verb: "Clear Exception Conditions", kind: "processing" },
            { verb: "RC <- 1", kind: "processing" },
            { verb: "P <- 1", kind: "processing" },
            { verb: "SABM", kind: "signal_lower" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_mod_128_sabme",
          guard: "mod_128",
          actions: [
            { verb: "Clear Exception Conditions", kind: "processing" },
            { verb: "RC <- 1", kind: "processing" },
            { verb: "P <- 1", kind: "processing" },
            { verb: "SABME", kind: "signal_lower" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Clear exception bookkeeping, set the retry counter and P flag,\nsend SABM or SABME depending on Mod 128 state, then start T1.\n",
      references: [],
    },
    {
      name: "Establish_Extended_Data_Link",
      paths: [
        {
          id: "t01_mod_8_sabm",
          guard: "not mod_128",
          actions: [
            { verb: "Clear Exception Conditions", kind: "processing" },
            { verb: "RC <- 1", kind: "processing" },
            { verb: "P <- 1", kind: "processing" },
            { verb: "SABM", kind: "signal_lower" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_mod_128_sabme",
          guard: "mod_128",
          actions: [
            { verb: "Clear Exception Conditions", kind: "processing" },
            { verb: "RC <- 1", kind: "processing" },
            { verb: "P <- 1", kind: "processing" },
            { verb: "SABME", kind: "signal_lower" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Shares its body with Establish_Data_Link (both subroutine-start\nnodes in the graphml flow into the same shared body at n48).\nFunctionally identical — the body's `Mod 128?` test picks\nSABM vs SABME so the caller's choice of name is informational.\nTracked separately because state-machine pages (figc4.2 vs\nfigc4.4) reference them by distinct names.\n",
      references: [],
    },
    {
      name: "Check_Need_For_Response",
      paths: [
        {
          id: "t01_command_poll_enquiry_response",
          guard: "command_and_p_eq_1",
          actions: [
            { verb: "Enquiry_Response_F_1", kind: "subroutine" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_response_f_unexpected_dl_error",
          guard: "not command_and_p_eq_1 and response_and_f_eq_1",
          actions: [
            { verb: "DL-ERROR Indication (A)", kind: "signal_upper" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t03_neither_silent_return",
          guard: "not command_and_p_eq_1 and not response_and_f_eq_1",
          actions: [],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Looks at incoming command/response role + P/F bit and either\nsends Enquiry_Response(F=1) (when it was a poll), surfaces a\nDL-ERROR (A) (response with F=1 when not expected), or returns\nsilently.\n",
      references: [],
    },
    {
      name: "UI_Check",
      paths: [
        {
          id: "t01_response_dl_error_q",
          guard: "not incoming_is_command",
          actions: [
            { verb: "DL-ERROR Indication (Q)", kind: "signal_upper" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_command_valid_unit_data",
          guard: "incoming_is_command and ui_info_field_valid",
          actions: [
            { verb: "DL-UNIT-DATA Indication", kind: "signal_upper" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t03_command_invalid_dl_error_k",
          guard: "incoming_is_command and not ui_info_field_valid",
          actions: [
            { verb: "DL-ERROR Indication (K)", kind: "signal_upper" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Validates a received UI frame. Rejects if it's a response (Q\nerror), accepts if info length ≤ N1 and the content is\noctet-aligned (DL-UNIT-DATA indication), or surfaces a K error.\n",
      references: [],
    },
    {
      name: "Select_T1_Value",
      paths: [
        {
          id: "t01_fresh_ack_iir",
          guard: "rc_eq_0",
          actions: [
            { verb: "SRT <- 7(SRT)/8 + (T1)/8 - (Remaining Time on T1 When Last Stopped)/8", kind: "processing" },
            { verb: "Next T1 <- 2 * SRT", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_retry_t1_expired",
          guard: "not rc_eq_0 and t1_expired",
          actions: [
            { verb: "Next T1 <- (RC*0.25)+SRT*2", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t03_no_change",
          guard: "not rc_eq_0 and not t1_expired",
          actions: [],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Recompute SRT (smoothed round-trip estimate) and the next T1\ntimeout. On a fresh-ack path (RC==0) the spec's IIR-style\nformula runs; on a retry path (RC > 0, T1 expired) we just\nbump T1V to next-attempt. Otherwise return without change.\n\nCanonical name `Select_T1_Value` (the figure's start label is\njust \"Select T1\" but the existing registry / state pages use\nthe longer form).\n",
      references: [],
    },
    {
      name: "Set_Version_2_0",
      paths: [
        {
          id: "t01_v2_0_defaults",
          guard: "",
          actions: [
            { verb: "Set Half Duplex", kind: "processing" },
            { verb: "Set Implicit Reject", kind: "processing" },
            { verb: "Modulo <- 8", kind: "processing" },
            { verb: "N1 <- 2048", kind: "processing" },
            { verb: "k <- 8", kind: "processing" },
            { verb: "T2 <- 3000", kind: "processing" },
            { verb: "N2 <- 10", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Configure all v2.0-specific parameters. Single multi-line\nprocessing box in the figure; transcribed as one action per\nline.\n",
      references: [],
    },
    {
      name: "Set_Version_2_2",
      paths: [
        {
          id: "t01_v2_2_defaults",
          guard: "",
          actions: [
            { verb: "Set Half Duplex", kind: "processing" },
            { verb: "Set Selective Reject", kind: "processing" },
            { verb: "Modulo <- 128", kind: "processing" },
            { verb: "N1 <- 2048", kind: "processing" },
            { verb: "k <- 32", kind: "processing" },
            { verb: "T2 <- 3000", kind: "processing" },
            { verb: "N2 <- 10", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "Configure all v2.2-specific parameters. Differs from v2.0 in\nSelective Reject (vs Implicit Reject), Modulo 128 (vs 8) and\nk = 32 (vs 8).\n",
      references: [],
    },
  ],
};
