using System.Net;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Packet.Node.Api;
using Packet.Node.Core.Auth;
using Packet.Node.Core.Beacons;
using Packet.Node.Core.Configuration;
using Packet.Node.Core.Console;
using Packet.Node.Core.Hosting;
using Packet.Node.Core.NetRom;
using Packet.Node.Core.Transports;

// The composition root for the Packet.NET node. This IS a Generic Host (the
// WebApplication builder gives us DI, config, hosted services, and logging),
// but slice 1 maps ZERO authenticated endpoints — only GET /healthz. The web
// server is present-but-inert: Kestrel binds from config, and the API / auth /
// UI arrive in later slices.

var configPath = ResolveConfigPath(args);
var dbPath = ResolveDbPath(args);

// ContentRoot = the app's own directory (where the published web UI's wwwroot
// sits), NOT the working directory. The packaged node runs with a WorkingDirectory
// of the writable StateDirectory (/var/lib/packetnet) while the binary + wwwroot
// live in /opt/packetnet/app, so defaulting ContentRoot to the CWD would make
// UseStaticFiles look in the wrong place. (Config/DB paths still resolve against
// the CWD by design — see ResolveConfigPath/ResolveDbPath.)
var builder = WebApplication.CreateBuilder(new WebApplicationOptions
{
    Args = args,
    ContentRootPath = AppContext.BaseDirectory,
});

// Build the config provider eagerly: it writes the first-start template if the
// file is absent and gives us the HTTP bind to hand to Kestrel before the host
// starts. Registered as the singleton IConfigProvider so the hosted service
// reuses this very instance (a single source of truth + a single file watcher).
// The eager provider logs to the bootstrap console; once the host is up,
// NodeHostedService logs through the configured pipeline.
using var bootstrapLoggers = LoggerFactory.Create(b => b.AddConsole());
var configProvider = new FileConfigProvider(
    configPath,
    TimeProvider.System,
    bootstrapLoggers.CreateLogger<FileConfigProvider>());
builder.Services.AddSingleton<IConfigProvider>(configProvider);
// The same instance is also the WRITE seam for the config API (PUT /config et al.).
// Registered separately so read-only consumers + the test fakes stay on the plain
// IConfigProvider; only this provider can persist an edit.
builder.Services.AddSingleton<IWritableConfigProvider>(configProvider);

// Teach the minimal-API JSON layer to (de)serialise the polymorphic TransportConfig
// union (a PUT /config body needs the `kind`-discriminated read; this is transparent
// for the existing GET serialisation). Web defaults (camelCase) are otherwise intact.
builder.Services.ConfigureHttpJsonOptions(o =>
    o.SerializerOptions.Converters.Add(new TransportConfigJsonConverter()));

// The routing-table persistence store (pdn.db). Created eagerly so it can hydrate
// NetRomService at start; registered as the singleton INetRomRoutingStore the hosted
// service injects. A store fault degrades to in-memory — it never fails the node.
var routingStore = new SqliteNetRomRoutingStore(
    dbPath,
    bootstrapLoggers.CreateLogger<SqliteNetRomRoutingStore>());
builder.Services.AddSingleton<INetRomRoutingStore>(routingStore);

// --- Web control-API auth foundation (default-OFF behind management.auth.enabled) ---
//
// The machinery is ALWAYS wired (user store, JWT issuing/validation, the scope
// policies + handler, the authentication/authorization middleware); only ENFORCEMENT
// is conditional on the flag (ScopeRequirementHandler passes through when off). So a
// node with auth off serves every endpoint exactly as before — turning auth on is a
// deliberate config change, never a silent behaviour shift.
//
// The user store + JWT signing key live in the same pdn.db as the routing table. The
// key is generated by a CSPRNG on first start and persisted (tokens survive a restart);
// it is never logged. If the store can't produce a key, JwtTokenService is left null —
// auth then cannot be enabled (login returns 503), but the node still boots.
var userStore = new SqliteUserStore(dbPath, bootstrapLoggers.CreateLogger<SqliteUserStore>());
builder.Services.AddSingleton<IUserStore>(userStore);

var signingKey = userStore.GetOrCreateSigningKey();
var accessTokenLifetime = TimeSpan.FromMinutes(configProvider.Current.Management.Auth.AccessTokenMinutes ?? 60);
JwtTokenService? tokenService =
    signingKey is not null ? new JwtTokenService(signingKey, accessTokenLifetime, TimeProvider.System) : null;
// Registered only when the signing key is available. When it is NOT (e.g. pdn.db
// unwritable), the service stays unregistered and the login handler's
// `[FromServices] JwtTokenService?` parameter resolves to null → login returns 503,
// while the node still boots and serves everything else. (The parameter MUST carry
// [FromServices]: without it, minimal-API inference can't classify an unregistered
// complex-type parameter and FAILS AT STARTUP — "Failure to infer … tokens | UNKNOWN"
// — aborting the whole host instead of degrading.)
if (tokenService is not null)
{
    builder.Services.AddSingleton(tokenService);
}

// Refresh-token rotation (auth part 2). The store lives in the same pdn.db (by hash
// only — the opaque token is never persisted in clear); the service wraps it with the
// one-time-use rotation + reuse-detection (theft-response) logic. Gated on the signing
// key exactly like JwtTokenService: with no key, login can't issue an access token, so
// a refresh token would be useless — leave the service unregistered (the handlers'
// `[FromServices] RefreshTokenService?` resolves to null → 503), node still boots.
var refreshTokenStore = new SqliteRefreshTokenStore(dbPath, bootstrapLoggers.CreateLogger<SqliteRefreshTokenStore>());
builder.Services.AddSingleton<IRefreshTokenStore>(refreshTokenStore);
if (tokenService is not null)
{
    var refreshLifetime = TimeSpan.FromMinutes(configProvider.Current.Management.Auth.RefreshTokenMinutes ?? 10080);
    builder.Services.AddSingleton(new RefreshTokenService(refreshTokenStore, refreshLifetime, TimeProvider.System));
}

// Login lockout: a sliding-window failure counter keyed per-username AND per-source-IP
// (5 failures / 5 min → 429, self-healing cooldown). Always registered (it's pure
// in-memory + the clock); the login handler's `[FromServices] LoginThrottle?` is still
// optional so an unregistered-service path can never abort startup.
builder.Services.AddSingleton(new LoginThrottle(TimeProvider.System));

// WebAuthn / passkeys (auth part 3, default-off behind management.auth.enabled). The
// credential STORE (public keys, sign counters, transports) lives in the same pdn.db as
// the users — a fault degrades to "no passkeys", never crashing the node. The challenge
// cache holds pending ceremonies in-memory (server-generated, single-use, expiring,
// user/session-bound — the anti-replay core). The per-request IFido2 verifier is built
// in the endpoints (WebAuthnFido2Builder) from the live config + the actual serving
// origin, so the RP-id/origin split (localhost-first) is handled there, not baked at
// startup. Registered as the SAME nullable-service contract as the JWT/refresh services:
// the credential store always registers (it degrades internally), and the host treats a
// null token/refresh service (no signing key) as "passkeys unusable" → 503, node boots.
var webAuthnStore = new SqliteWebAuthnCredentialStore(dbPath, bootstrapLoggers.CreateLogger<SqliteWebAuthnCredentialStore>());
builder.Services.AddSingleton<IWebAuthnCredentialStore>(webAuthnStore);
builder.Services.AddSingleton(new WebAuthnChallengeCache(TimeProvider.System));

// Over-RF sysop-code (TOTP) enrolment (auth part 4, enrolment half, default-off behind
// management.auth.enabled). The per-user secret + callsign + replay counter live on the
// existing user store (pdn.db) — added additively, degrade-safe like the rest. The
// pending-enrolment cache holds in-flight enrolments in-memory (server-minted secret,
// single-use, expiring — never persisted until the user confirms a code), mirroring the
// WebAuthn challenge cache. Always registered (pure in-memory + the clock); the endpoint's
// `TotpEnrollmentCache?` stays optional so an unregistered-service path can never abort
// startup. The console SYSOP gate that VERIFIES a presented code over a packet session is a
// separate piece — it consumes IUserStore.FindByCallsign + TotpService, which this readies.
builder.Services.AddSingleton(new TotpEnrollmentCache(TimeProvider.System));

// The RFC-6238 verifier (stateless over the clock — the single-use replay guard rides the
// persisted per-user counter, not in-memory state). Registered so the host injects it into
// NodeHostedService for the over-RF SYSOP gate; the enrolment endpoints construct their own
// over the request clock. With it registered (and IUserStore above), an auth-enabled node's
// console gains the SYSOP elevation command — inert until a user enrols a TOTP credential.
builder.Services.AddSingleton(new TotpService(TimeProvider.System));

// Authentication: JWT bearer validated against THIS node's signing key/issuer/audience
// (HS256 only). Always registered so a token presented when auth is on is validated;
// when the key is unavailable the validator gets a throwaway parameters object that
// fails every token (auth simply can't be used). The middleware never CHALLENGES on its
// own — the per-endpoint scope policy decides, and that passes through when auth is off.
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        if (tokenService is not null)
        {
            options.TokenValidationParameters = tokenService.ValidationParameters;
        }
        else
        {
            // No signing key → reject every token (validate against an impossible key set).
            options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
            {
                ValidateIssuer = false,
                ValidateAudience = false,
                ValidateLifetime = false,
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = new Microsoft.IdentityModel.Tokens.SymmetricSecurityKey(new byte[32]),
                ValidAlgorithms = [Microsoft.IdentityModel.Tokens.SecurityAlgorithms.HmacSha256],
            };
        }

        // SSE token-by-query: a browser EventSource can't set an Authorization
        // header, so the live feeds accept the JWT as a `?access_token=` query
        // param. Restricted to the SSE paths only (so we don't normalise
        // tokens-in-URLs across the API — they can leak into logs/referrers) and
        // only when no bearer header was supplied. The token is still fully
        // validated by the same pipeline; the query is just where it's read from.
        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                if (string.IsNullOrEmpty(context.Token))
                {
                    var path = context.HttpContext.Request.Path;
                    bool isSse = path.StartsWithSegments("/api/v1/events")
                        || (path.StartsWithSegments("/api/v1/sessions") && path.Value?.EndsWith("/stream", StringComparison.Ordinal) == true);
                    if (isSse)
                    {
                        var queryToken = context.Request.Query["access_token"];
                        if (!string.IsNullOrEmpty(queryToken))
                        {
                            context.Token = queryToken;
                        }
                    }
                }
                return Task.CompletedTask;
            },
        };
    });

// Authorization: the read/operate/admin scope policies, evaluated by the
// flag-aware ScopeRequirementHandler (registered scoped so it reads the live config).
builder.Services.AddAuthorization(options => options.AddPdnScopePolicies());
builder.Services.AddScoped<IAuthorizationHandler, ScopeRequirementHandler>();

builder.Services.AddSingleton<ITransportFactory>(TransportFactory.Instance);
builder.Services.AddSingleton(TimeProvider.System);
// Holds operator-initiated connect-out sessions as interactive consoles (the web
// Sessions drawer reads their output over SSE + types into them). Disposed on host
// shutdown (IAsyncDisposable) → each adopted connection gets a clean DISC.
builder.Services.AddSingleton<SysopConsoleManager>();
// The ID-beacon service: a singleton over the live config + clock. The hosted service
// injects it (and passes it to the supervisor, which attaches it per port) — it is
// inert until a port whose effective beacon is enabled comes up (default-off).
builder.Services.AddSingleton<BeaconService>();
// Register the hosted service as a singleton AND as the hosted service, so the
// control-API endpoint handlers can inject it and read its live Supervisor /
// NetRom handles (the read API projects the node's state from these).
builder.Services.AddSingleton<NodeHostedService>();
builder.Services.AddHostedService(sp => sp.GetRequiredService<NodeHostedService>());

// Bind Kestrel from the node config's management.http section, plus an optional TLS
// listener (management.https). HTTPS is opt-in; the plain HTTP listener is unchanged.
var management = configProvider.Current.Management;
var http = management.Http;
var https = management.Https;

// Resolve the HTTPS cert ONCE, before binding. A null result (TLS off, or a cert that
// couldn't be loaded/generated — logged by the provider) just means we skip the HTTPS
// endpoint; HTTP still serves, so a TLS misconfig never takes the node down.
System.Security.Cryptography.X509Certificates.X509Certificate2? httpsCert = null;
if (https.Enabled)
{
    // Persist a generated self-signed cert beside the db (the writable StateDirectory
    // on the packaged node), e.g. /var/lib/packetnet/certs/server.pfx.
    var certDir = Path.GetDirectoryName(dbPath) is { Length: > 0 } d ? d : ".";
    var selfSignedPath = Path.Combine(certDir, "certs", "server.pfx");
    var bindIp = IPAddress.TryParse(https.Bind, out var hb) ? hb : IPAddress.Loopback;
    var sanIps = new List<IPAddress> { IPAddress.Loopback, IPAddress.IPv6Loopback };
    if (!Equals(bindIp, IPAddress.Any) && !Equals(bindIp, IPAddress.IPv6Any) && !sanIps.Contains(bindIp))
    {
        sanIps.Add(bindIp);
    }
    var commonName = string.IsNullOrWhiteSpace(configProvider.Current.Identity.Callsign)
        ? "packetnet"
        : configProvider.Current.Identity.Callsign;
    httpsCert = Packet.Node.Core.TlsCertificateProvider.Resolve(
        https, selfSignedPath, commonName,
        sanDnsNames: ["localhost", Environment.MachineName],
        sanIpAddresses: sanIps,
        clock: TimeProvider.System,
        logger: bootstrapLoggers.CreateLogger("Packet.Node.Tls"));
}

builder.WebHost.ConfigureKestrel(options =>
{
    var address = IPAddress.TryParse(http.Bind, out var ip) ? ip : IPAddress.Loopback;
    options.Listen(address, http.Port);

    if (httpsCert is not null)
    {
        var httpsAddress = IPAddress.TryParse(https.Bind, out var hip) ? hip : IPAddress.Loopback;
        options.Listen(httpsAddress, https.Port, listenOptions => listenOptions.UseHttps(httpsCert));
    }
});

var app = builder.Build();

// Authentication + authorization run for every request. With auth disabled they are
// effectively inert (no [Authorize] challenges, and the scope policies pass through via
// ScopeRequirementHandler), so the default-off pipeline behaves exactly as before.
app.UseAuthentication();
app.UseAuthorization();

// Unauthenticated liveness probe. ALWAYS open — never gated.
app.MapGet("/healthz", () => Results.Ok(new { status = "ok" }));

// Auth foundation endpoints. /setup/state, /auth/login, /setup are ALWAYS open (the
// bootstrap path — you can't present a token before you have an account); the /users
// group is returned so we can gate it `admin` (the gate is a no-op when auth is off).
var usersGroup = app.MapPdnAuthApi();
usersGroup.RequireAuthorization(PdnAuthPolicies.Admin);

// WebAuthn / passkeys (auth part 3). The assert (passwordless-login) endpoints are
// ALWAYS open — a login can't carry a bearer token. The register + credential-management
// group is gated `read`: a logged-in user enrols/manages a passkey for THEMSELVES (the
// username comes from the authenticated principal, never the body), and read is the floor
// a self-service "manage my own login" action sits at — any authenticated user may add a
// passkey. The gate is a no-op when auth is off (and register/complete then 409s, since
// there is no authenticated "self" to enrol for). Mapped before the catch-all so the
// specific /api/v1/* routes win.
var webAuthnGroup = app.MapPdnWebAuthnApi();
webAuthnGroup.RequireAuthorization(PdnAuthPolicies.Read);

// Over-RF sysop-code (TOTP) enrolment (auth part 4). Self-service: a logged-in user enrols
// / inspects / removes the rolling code for THEMSELVES (the username comes from the
// authenticated principal, never the body), so the group is gated `read` — the same floor
// as the passkey register group. The gate is a no-op when auth is off (and enroll then 409s,
// since there is no authenticated "self" to enrol for). Mapped before the catch-all so the
// specific /api/v1/* routes win.
var totpGroup = app.MapPdnTotpApi();
totpGroup.RequireAuthorization(PdnAuthPolicies.Read);

// Slice 3 control API (read endpoints). Mapped BEFORE the SPA fallback so /api/*
// and /healthz win; everything else falls through to index.html for the React
// client router. (Auth is a later step — these are read-only and the node binds
// 127.0.0.1 by default. The live SSE feed for the monitor is step 1b.)
app.MapPdnReadApi();

// Slice 3 step 1b: the live SSE frame feed the web monitor's EventSource
// consumes (GET /api/v1/events). Mapped after the read API and before the
// catch-all; the specific route wins over /api/{**rest} regardless of order.
app.MapPdnEvents();

// Slice 3 step 2: the write-side config API (PUT /config + /config/raw + the
// raw-YAML GET) the web editor persists edits through. Mapped after the read API
// and before the catch-all; the specific routes win over /api/{**rest} regardless
// of order. (Auth is a later step — unauthenticated, node binds 127.0.0.1.)
app.MapPdnConfigApi();

// Slice 3 step 3: the port-management API (POST/PUT/DELETE /ports + the
// /ports/{id}/lifecycle up/down) the web Ports screen mutates ports through. Every
// change is a config edit persisted through the same write seam as PUT /config.
// Mapped after the config API and before the catch-all; the specific routes win over
// /api/{**rest} regardless of order. (Auth is a later step — unauthenticated, node
// binds 127.0.0.1.)
app.MapPdnPortsApi();

// Slice 3 step 4: the direct-supervisor session actions + ping — connect-out
// (POST /sessions), disconnect (DELETE /sessions/{id}), send-line
// (POST /sessions/{id}/send), and the connectionless TEST /ping (deferred 501).
// These run under the host's exclusive gate so a web action never races a config
// reconcile. Mapped after the port API and before the catch-all; the specific routes
// win over /api/{**rest} regardless of order. (Auth is a later step — unauthenticated,
// node binds 127.0.0.1.)
app.MapPdnSessionsApi();

// An unknown /api/* path returns 404 — it must NOT fall through to the SPA
// index.html below (the catch-all is less specific than the real /api/v1/*
// routes, so those still win).
app.Map("/api/{**rest}", () => Results.NotFound());

// Serve the built web UI (web/packetnet-ui → wwwroot) + SPA client-side routing:
// any other unmatched, non-file route returns index.html so the React router
// can handle it (deep links like /monitor, /ports).
app.UseDefaultFiles();
app.UseStaticFiles();
app.MapFallbackToFile("index.html");

app.Run();

static string ResolveConfigPath(string[] args)
{
    // --config <path> wins, then PACKETNET_CONFIG, then a sensible default in the
    // working directory.
    for (int i = 0; i < args.Length - 1; i++)
    {
        if (args[i] is "--config" or "-c")
        {
            return args[i + 1];
        }
    }
    var env = Environment.GetEnvironmentVariable("PACKETNET_CONFIG");
    return !string.IsNullOrWhiteSpace(env) ? env : Path.Combine(Directory.GetCurrentDirectory(), "packetnet.yaml");
}

static string ResolveDbPath(string[] args)
{
    // --db <path> wins, then PACKETNET_DB, then pdn.db in the working directory —
    // which on the packaged node is the writable StateDirectory (/var/lib/packetnet).
    for (int i = 0; i < args.Length - 1; i++)
    {
        if (args[i] is "--db")
        {
            return args[i + 1];
        }
    }
    var env = Environment.GetEnvironmentVariable("PACKETNET_DB");
    return !string.IsNullOrWhiteSpace(env) ? env : Path.Combine(Directory.GetCurrentDirectory(), "pdn.db");
}

/// <summary>Exposed so the WebApplicationFactory-based host test can boot this
/// exact composition root.</summary>
public partial class Program;
