using System.Security.Claims;
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;

namespace Packet.Node.Core.Auth;

/// <summary>
/// Issues and validates the web control-API access tokens (HS256 JWTs). Web-free
/// (it depends only on the IdentityModel token primitives, not ASP.NET), so it
/// lives in <c>Packet.Node.Core</c>; the host wires the JwtBearer <em>middleware</em>
/// around the same <see cref="ValidationParameters"/>.
/// </summary>
/// <remarks>
/// <para>
/// <b>HS256</b> (HMAC-SHA-256) with the 256-bit symmetric key from the user store
/// (generated by a CSPRNG, persisted in <c>pdn.db</c> so tokens survive a restart,
/// never logged). HS256 is the right choice for a single-process node that both
/// issues and validates: there is no third party that needs to verify without the
/// secret, so an asymmetric key pair would add key-management cost for no benefit.
/// </para>
/// <para>
/// <b>Claims:</b> <c>sub</c> = username and a single <c>scope</c> claim
/// (<see cref="AuthScopes"/> - the highest scope the user holds; the implication
/// admin ⊃ operate ⊃ read is applied at the authorization check, not by carrying
/// every scope). Standard <c>iat</c>/<c>nbf</c>/<c>exp</c> plus a fixed issuer +
/// audience the validator pins.
/// </para>
/// <para>
/// <b>No wall-clock (repo rule §2.7):</b> the issue instant and expiry come from
/// the injected <see cref="TimeProvider"/>, and the validator is given the same
/// clock so expiry checks are deterministic + testable.
/// </para>
/// <para>
/// <b>Session model: short access token + rotating refresh token.</b> The access JWT
/// is deliberately short-lived (default 60 minutes); the session is carried by an
/// opaque refresh token minted alongside it by <see cref="RefreshTokenService"/>. The
/// client exchanges that token at <c>/auth/refresh</c> for a fresh pair (one-time use,
/// rotated on every exchange); replaying a consumed token outside the reuse-leeway
/// window revokes the whole family (the theft response), and <c>/auth/logout</c>
/// revokes it explicitly. Refresh tokens are stored only as a SHA-256 hash in
/// <c>pdn.db</c>, so a database read never yields a usable token.
/// </para>
/// </remarks>
public sealed class JwtTokenService
{
    /// <summary>The fixed JWT issuer the node stamps + the validator pins.</summary>
    public const string Issuer = "packet.net-node";

    /// <summary>The audience for the <b>web control-API</b> credentials - the panel
    /// login / refresh tokens. The default audience <see cref="Issue(string,string)"/>
    /// stamps.</summary>
    public const string Audience = "packet.net-control-api";

    /// <summary>The audience for <b>MCP</b> credentials - the static MCP bearer
    /// (<c>/api/v1/mcp/token</c>) and the OAuth-issued connector tokens. Distinct from
    /// <see cref="Audience"/> so an MCP token cannot drive the wider control API:
    /// the JwtBearer middleware authenticates both audiences, but each endpoint's
    /// authorization policy pins exactly one (the <c>read/operate/admin</c> gates pin
    /// the control-API audience; the MCP gate pins this). Mints stay segregated even
    /// though both ride the same signing key + issuer.</summary>
    public const string McpAudience = "packet.net-mcp";

    private static readonly JsonWebTokenHandler Handler = new();

    private readonly SymmetricSecurityKey signingKey;
    private readonly TimeProvider clock;
    private readonly TimeSpan lifetime;

    /// <summary>
    /// Construct over the persisted signing key and the access-token lifetime.
    /// </summary>
    /// <param name="signingKey">The 256-bit HS256 key (from
    /// <see cref="IUserStore.GetOrCreateSigningKey"/>). Must be ≥ 32 bytes.</param>
    /// <param name="lifetime">Access-token lifetime (≈ 1h by default).</param>
    /// <param name="clock">The injected clock (token <c>iat</c>/<c>exp</c> + the
    /// validator's expiry check ride this - no wall-clock).</param>
    public JwtTokenService(byte[] signingKey, TimeSpan lifetime, TimeProvider clock)
    {
        ArgumentNullException.ThrowIfNull(signingKey);
        ArgumentNullException.ThrowIfNull(clock);
        if (signingKey.Length < 32)
        {
            throw new ArgumentException("HS256 signing key must be at least 256 bits (32 bytes).", nameof(signingKey));
        }
        if (lifetime <= TimeSpan.Zero)
        {
            throw new ArgumentOutOfRangeException(nameof(lifetime), "Token lifetime must be positive.");
        }
        this.signingKey = new SymmetricSecurityKey(signingKey);
        this.lifetime = lifetime;
        this.clock = clock;
    }

    /// <summary>
    /// Issue an access token for <paramref name="username"/> carrying
    /// <paramref name="scope"/>, expiring <see cref="lifetime"/> from now. Returns
    /// the compact JWT string and its absolute expiry instant.
    /// </summary>
    public (string Token, DateTimeOffset ExpiresAt) Issue(string username, string scope)
        => Issue(username, scope, lifetime, Audience);

    /// <summary>
    /// Issue a token with an explicit <paramref name="lifetime"/> instead of the
    /// service default, for the <b>control-API</b> audience. Used for the long-lived
    /// MCP-adjacent control tokens; for an MCP-audience token use the
    /// <see cref="Issue(string,string,TimeSpan,string)"/> overload.
    /// </summary>
    public (string Token, DateTimeOffset ExpiresAt) Issue(string username, string scope, TimeSpan lifetime)
        => Issue(username, scope, lifetime, Audience);

    /// <summary>
    /// Issue a token with an explicit <paramref name="lifetime"/> and an explicit
    /// <paramref name="audience"/> (one of <see cref="Audience"/> / <see cref="McpAudience"/>).
    /// Used for the long-lived MCP bearer token (Phase 8): a Claude Code config holds a
    /// static header, so it needs a token that outlives the 60-min access-token default.
    /// Same issuer/scope claim + signing key - so it validates through the existing
    /// JwtBearer middleware unchanged; the <c>aud</c> is what segregates an MCP token
    /// from a control-API token at the authorization gate. The longer the lifetime, the
    /// more a leaked token matters - callers default the MCP token to the <c>read</c> scope.
    /// </summary>
    public (string Token, DateTimeOffset ExpiresAt) Issue(string username, string scope, TimeSpan lifetime, string audience)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(username);
        ArgumentException.ThrowIfNullOrWhiteSpace(scope);
        ArgumentException.ThrowIfNullOrWhiteSpace(audience);
        ArgumentOutOfRangeException.ThrowIfLessThanOrEqual(lifetime, TimeSpan.Zero);

        var now = clock.GetUtcNow();
        var expires = now + lifetime;

        var descriptor = new SecurityTokenDescriptor
        {
            Issuer = Issuer,
            Audience = audience,
            IssuedAt = now.UtcDateTime,
            NotBefore = now.UtcDateTime,
            Expires = expires.UtcDateTime,
            Claims = new Dictionary<string, object>
            {
                [JwtRegisteredClaimNames.Sub] = username,
                [AuthScopes.ScopeClaim] = scope,
            },
            SigningCredentials = new SigningCredentials(signingKey, SecurityAlgorithms.HmacSha256),
        };

        return (Handler.CreateToken(descriptor), expires);
    }

    /// <summary>
    /// The <see cref="TokenValidationParameters"/> the host's JwtBearer middleware
    /// validates with - pinned to this node's signing key, issuer and audience,
    /// HS256 only, and a <see cref="TokenValidationParameters.LifetimeValidator"/>
    /// driven by the injected clock so expiry is deterministic + testable (repo
    /// rule §2.7: no wall-clock - the validator reads <see cref="TimeProvider"/>,
    /// not <see cref="DateTime.UtcNow"/>). No clock skew (the node is both issuer
    /// and validator on one clock).
    /// </summary>
    public TokenValidationParameters ValidationParameters => new()
    {
        ValidateIssuer = true,
        ValidIssuer = Issuer,
        ValidateAudience = true,
        // Authenticate BOTH audiences here; the per-endpoint policy pins which one is
        // allowed where (control-API gates vs the MCP gate) - that's what keeps an MCP
        // token off the wider control API.
        ValidAudiences = [Audience, McpAudience],
        ValidateIssuerSigningKey = true,
        IssuerSigningKey = signingKey,
        ValidateLifetime = true,
        ClockSkew = TimeSpan.Zero,
        LifetimeValidator = LifetimeIsValid,
        ValidAlgorithms = [SecurityAlgorithms.HmacSha256],
        NameClaimType = JwtRegisteredClaimNames.Sub,
    };

    // Lifetime check against the injected clock (not DateTime.UtcNow): the token is
    // valid iff now ∈ [nbf, exp). A missing exp is treated as invalid (every token
    // we issue carries one). No skew - the node issues + validates on one clock.
    private bool LifetimeIsValid(DateTime? notBefore, DateTime? expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
    {
        if (expires is null)
        {
            return false;
        }
        var now = clock.GetUtcNow().UtcDateTime;
        if (notBefore is { } nbf && now < nbf)
        {
            return false;
        }
        return now < expires.Value;
    }

    /// <summary>
    /// Validate a token directly (used by the unit tests; the host path validates
    /// through the JwtBearer middleware over <see cref="ValidationParameters"/>).
    /// Returns the principal on success, or null if the token is invalid / expired /
    /// tampered.
    /// </summary>
    public async Task<ClaimsPrincipal?> ValidateAsync(string token)
    {
        ArgumentNullException.ThrowIfNull(token);
        var result = await Handler.ValidateTokenAsync(token, ValidationParameters).ConfigureAwait(false);
        return result.IsValid ? new ClaimsPrincipal(result.ClaimsIdentity) : null;
    }
}
