using System.Globalization;
using System.Security.Cryptography;
using Dapper;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Packet.Node.Core.Auth;

/// <summary>
/// The SQLite-backed <see cref="IUserStore"/>: persists the web control-API users
/// and the JWT signing key to the same consolidated <c>pdn.db</c> the NET/ROM
/// routing table lives in. Raw SQL via Dapper (no EF, per the node host's
/// persistence decision), mirroring <c>SqliteNetRomRoutingStore</c>.
/// </summary>
/// <remarks>
/// <para>
/// Two tables on its own <c>PRAGMA user_version</c> namespace would clash with the
/// routing store's, so the auth schema is versioned by a <c>meta</c> sentinel row
/// instead (the routing store owns <c>user_version</c>; reusing it here would make
/// the two stores fight over the same counter). The <c>user</c> table holds the
/// accounts; a <c>auth_meta</c> table holds the signing key (and the schema marker).
/// </para>
/// <para>
/// <b>Resilient.</b> Every operation is wrapped: a schema/open failure logs and
/// leaves the node running (auth simply can't be used); reads return null/empty on
/// fault; writes return false. Persistence can never take the node down. WAL mode,
/// a fresh pooled connection per call — the same discipline as the routing store —
/// so the store is safe to share across the request threads.
/// </para>
/// <para>
/// <b>The signing key is a secret.</b> It is generated by
/// <see cref="RandomNumberGenerator"/> (256 bits) on first start, stored as
/// base64 in <c>auth_meta</c>, and <em>never</em> logged — the log messages here
/// reference only the db path, never a key value.
/// </para>
/// </remarks>
public sealed partial class SqliteUserStore : IUserStore
{
    private const string SigningKeyKey = "jwt_signing_key";
    private const int SigningKeyBytes = 32;   // 256-bit HS256 key

    private const string SchemaSql = """
        CREATE TABLE IF NOT EXISTS user (
            username       TEXT PRIMARY KEY,
            password_hash  TEXT NOT NULL,
            scopes         TEXT NOT NULL,
            created_utc    TEXT NOT NULL,
            last_login_utc TEXT NULL);
        CREATE TABLE IF NOT EXISTS auth_meta (
            key   TEXT PRIMARY KEY,
            value TEXT NOT NULL);
        """;

    // The over-RF TOTP columns, added additively to the existing user table. SQLite has
    // no ADD COLUMN IF NOT EXISTS, so each is applied guarded (PRAGMA table_info check +
    // a duplicate-column catch) — see EnsureTotpColumns. A pre-TOTP db (no columns) opens
    // fine and gains them; re-running is a no-op.
    private static readonly (string Name, string Ddl)[] TotpColumns =
    [
        ("callsign",          "ALTER TABLE user ADD COLUMN callsign TEXT NULL;"),
        ("totp_secret",       "ALTER TABLE user ADD COLUMN totp_secret TEXT NULL;"),
        ("last_totp_counter", "ALTER TABLE user ADD COLUMN last_totp_counter INTEGER NULL;"),
    ];

    // The full user projection (all columns, base + TOTP), aliased to UserRow's
    // properties. Shared by FindByUsername / FindByCallsign / List so every read path
    // round-trips the TOTP fields.
    private const string UserSelectColumns =
        "username AS Username, password_hash AS PasswordHash, scopes AS Scopes, " +
        "created_utc AS CreatedUtc, last_login_utc AS LastLoginUtc, " +
        "callsign AS Callsign, totp_secret AS TotpSecret, last_totp_counter AS LastTotpCounter";

    private readonly string connectionString;
    private readonly ILogger<SqliteUserStore> logger;

    /// <summary>Open (creating if absent) the user store at <paramref name="dbPath"/>
    /// and ensure its schema. A schema/open failure is logged, not thrown — the node
    /// still boots, just with auth unavailable.</summary>
    public SqliteUserStore(string dbPath, ILogger<SqliteUserStore>? logger = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(dbPath);
        this.logger = logger ?? NullLogger<SqliteUserStore>.Instance;
        connectionString = new SqliteConnectionStringBuilder { DataSource = dbPath }.ToString();
        EnsureSchema();
    }

    private SqliteConnection Open()
    {
        var conn = new SqliteConnection(connectionString);
        conn.Open();
        return conn;
    }

    private void EnsureSchema()
    {
        try
        {
            using var conn = Open();
            conn.Execute("PRAGMA journal_mode=WAL;");
            conn.Execute(SchemaSql);
            EnsureTotpColumns(conn);
        }
        catch (SqliteException ex)
        {
            LogSchemaFailed(ex, connectionString);
        }
    }

    // Additively migrate the existing user table to carry the over-RF TOTP columns. The
    // webauthn/refresh stores use CREATE TABLE IF NOT EXISTS, but the user table predates
    // these columns and must keep its rows, so we ALTER TABLE ADD COLUMN instead. SQLite
    // has no ADD COLUMN IF NOT EXISTS — so we read PRAGMA table_info(user) once and only
    // add the columns that are missing, and additionally swallow a "duplicate column name"
    // SqliteException (belt-and-braces against a race / a stale read). Idempotent.
    private void EnsureTotpColumns(SqliteConnection conn)
    {
        var existing = conn.Query<string>("SELECT name FROM pragma_table_info('user');")
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        foreach (var (name, ddl) in TotpColumns)
        {
            if (existing.Contains(name))
            {
                continue;
            }
            try
            {
                conn.Execute(ddl);
            }
            catch (SqliteException ex) when (ex.Message.Contains("duplicate column name", StringComparison.OrdinalIgnoreCase))
            {
                // Already present (added concurrently / between the read and here) — fine.
            }
        }

        // Enforce callsign uniqueness at the DB level (a partial unique index — only
        // non-NULL callsigns are constrained, so the many users with no TOTP enrolled
        // don't collide on NULL). This is what makes the binding safe: it closes the
        // SELECT-then-UPDATE race in SetTotpSecret (a racing bind fails the index → the
        // UPDATE throws → SetTotpSecret returns false), and it guarantees FindByCallsign
        // can never see two rows for one callsign. Idempotent (IF NOT EXISTS). Wrapped so
        // a pre-existing duplicate (shouldn't happen) degrades to "no index" rather than
        // taking the node down — uniqueness then falls back to the SELECT check.
        try
        {
            conn.Execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS ix_user_callsign " +
                "ON user(callsign) WHERE callsign IS NOT NULL;");
        }
        catch (SqliteException ex)
        {
            LogSchemaFailed(ex, connectionString);
        }
    }

    /// <inheritdoc/>
    public int Count()
    {
        try
        {
            using var conn = Open();
            return (int)conn.ExecuteScalar<long>("SELECT COUNT(*) FROM user;");
        }
        catch (SqliteException ex)
        {
            // A broken store reads as zero users → "needs setup". That is the safe
            // failure mode: it can't silently authenticate anyone, and the operator
            // sees the setup probe rather than a locked-out node.
            LogReadFailed(ex, connectionString);
            return 0;
        }
    }

    /// <inheritdoc/>
    public UserRecord? FindByUsername(string username)
    {
        ArgumentNullException.ThrowIfNull(username);
        try
        {
            using var conn = Open();
            var row = conn.QuerySingleOrDefault<UserRow>(
                "SELECT " + UserSelectColumns + " FROM user WHERE username = @u;",
                new { u = username });
            return row is null ? null : ToRecord(row);
        }
        catch (Exception ex) when (ex is SqliteException or FormatException)
        {
            LogReadFailed(ex, connectionString);
            return null;
        }
    }

    /// <inheritdoc/>
    public UserRecord? FindByCallsign(string callsign)
    {
        ArgumentNullException.ThrowIfNull(callsign);
        try
        {
            using var conn = Open();
            // Case-insensitive match on the callsign column. COLLATE NOCASE is ASCII-only,
            // which is exactly right for callsigns (A–Z / 0–9). A NULL callsign (no TOTP
            // enrolled) never matches a non-empty lookup.
            var row = conn.QuerySingleOrDefault<UserRow>(
                "SELECT " + UserSelectColumns +
                " FROM user WHERE callsign IS NOT NULL AND callsign = @c COLLATE NOCASE;",
                new { c = callsign });
            return row is null ? null : ToRecord(row);
        }
        catch (Exception ex) when (ex is SqliteException or FormatException)
        {
            LogReadFailed(ex, connectionString);
            return null;
        }
    }

    /// <inheritdoc/>
    public IReadOnlyList<UserRecord> List()
    {
        try
        {
            using var conn = Open();
            var rows = conn.Query<UserRow>(
                "SELECT " + UserSelectColumns + " FROM user ORDER BY username;").ToList();
            var users = new List<UserRecord>(rows.Count);
            foreach (var row in rows)
            {
                users.Add(ToRecord(row));
            }
            return users;
        }
        catch (Exception ex) when (ex is SqliteException or FormatException)
        {
            LogReadFailed(ex, connectionString);
            return [];
        }
    }

    /// <inheritdoc/>
    public bool Create(UserRecord user)
    {
        ArgumentNullException.ThrowIfNull(user);
        try
        {
            using var conn = Open();
            conn.Execute(
                "INSERT INTO user (username, password_hash, scopes, created_utc, last_login_utc, " +
                "callsign, totp_secret, last_totp_counter) " +
                "VALUES (@u, @h, @s, @c, @l, @call, @secret, @counter);",
                new
                {
                    u = user.Username,
                    h = user.PasswordHash,
                    s = user.Scope,
                    c = Stamp(user.CreatedUtc),
                    l = user.LastLoginUtc is { } when ? Stamp(when) : null,
                    call = user.Callsign,
                    secret = user.TotpSecret,
                    counter = user.LastTotpCounter,
                });
            return true;
        }
        catch (SqliteException ex) when (ex.SqliteErrorCode == 19)
        {
            // SQLITE_CONSTRAINT (19) — the UNIQUE username already exists. A normal
            // "duplicate user" outcome, not a fault: return false without logging noise.
            return false;
        }
        catch (SqliteException ex)
        {
            LogWriteFailed(ex, connectionString);
            return false;
        }
    }

    /// <inheritdoc/>
    public bool Delete(string username)
    {
        ArgumentNullException.ThrowIfNull(username);
        try
        {
            using var conn = Open();
            int rows = conn.Execute("DELETE FROM user WHERE username = @u;", new { u = username });
            return rows > 0;
        }
        catch (SqliteException ex)
        {
            LogWriteFailed(ex, connectionString);
            return false;
        }
    }

    /// <inheritdoc/>
    public void UpdateLastLogin(string username, DateTimeOffset whenUtc)
    {
        ArgumentNullException.ThrowIfNull(username);
        try
        {
            using var conn = Open();
            conn.Execute(
                "UPDATE user SET last_login_utc = @l WHERE username = @u;",
                new { u = username, l = Stamp(whenUtc) });
        }
        catch (SqliteException ex)
        {
            // Best-effort: a failed last-login stamp must never fail the login itself.
            LogWriteFailed(ex, connectionString);
        }
    }

    /// <inheritdoc/>
    public bool SetTotpSecret(string username, string secret, string callsign)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(username);
        ArgumentException.ThrowIfNullOrWhiteSpace(secret);
        ArgumentException.ThrowIfNullOrWhiteSpace(callsign);
        try
        {
            using var conn = Open();

            // Enforce callsign uniqueness across users (case-insensitive). If the callsign
            // is already bound to a DIFFERENT account, refuse — the caller turns this into
            // a 409. (Re-binding the SAME callsign to its own user, e.g. a re-enrol, is
            // allowed.) Done in the same connection as the update; a fresh pooled
            // connection per call is already serialised by SQLite's file lock under WAL.
            var owner = conn.ExecuteScalar<string?>(
                "SELECT username FROM user WHERE callsign IS NOT NULL AND callsign = @c COLLATE NOCASE;",
                new { c = callsign });
            if (owner is not null && !string.Equals(owner, username, StringComparison.Ordinal))
            {
                return false;
            }

            int rows = conn.Execute(
                "UPDATE user SET totp_secret = @secret, callsign = @call, last_totp_counter = NULL " +
                "WHERE username = @u;",
                new { u = username, secret, call = callsign });
            return rows > 0;
        }
        catch (SqliteException ex)
        {
            LogWriteFailed(ex, connectionString);
            return false;
        }
    }

    /// <inheritdoc/>
    public bool ClearTotp(string username)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(username);
        try
        {
            using var conn = Open();
            // Only count it as a change when the user actually had a credential, so a
            // double-clear (or a clear on a never-enrolled user) reads as "nothing changed".
            int rows = conn.Execute(
                "UPDATE user SET totp_secret = NULL, callsign = NULL, last_totp_counter = NULL " +
                "WHERE username = @u AND (totp_secret IS NOT NULL OR callsign IS NOT NULL);",
                new { u = username });
            return rows > 0;
        }
        catch (SqliteException ex)
        {
            LogWriteFailed(ex, connectionString);
            return false;
        }
    }

    /// <inheritdoc/>
    public bool UpdateTotpCounter(string username, long counter)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(username);
        try
        {
            using var conn = Open();
            conn.Execute(
                "UPDATE user SET last_totp_counter = @counter WHERE username = @u;",
                new { u = username, counter });
            return true;
        }
        catch (SqliteException ex)
        {
            // Unlike UpdateLastLogin this is NOT silently swallowed: the over-RF gate must
            // know the replay high-water mark could not be persisted (so it can refuse to
            // treat the just-accepted code as consumed and avoid re-opening a replay window).
            LogWriteFailed(ex, connectionString);
            return false;
        }
    }

    /// <inheritdoc/>
    public byte[]? GetOrCreateSigningKey()
    {
        try
        {
            using var conn = Open();

            var existing = conn.ExecuteScalar<string?>(
                "SELECT value FROM auth_meta WHERE key = @k;", new { k = SigningKeyKey });
            if (existing is not null && TryFromBase64(existing, out var key) && key.Length == SigningKeyBytes)
            {
                return key;
            }

            // First start (or an unreadable/short stored value): generate + persist a
            // fresh 256-bit key. INSERT-OR-REPLACE so a malformed prior value is healed.
            var fresh = RandomNumberGenerator.GetBytes(SigningKeyBytes);
            conn.Execute(
                "INSERT INTO auth_meta (key, value) VALUES (@k, @v) " +
                "ON CONFLICT(key) DO UPDATE SET value = @v;",
                new { k = SigningKeyKey, v = Convert.ToBase64String(fresh) });
            return fresh;
        }
        catch (SqliteException ex)
        {
            // The key can neither be read nor persisted → auth cannot be enabled safely.
            // (Never log the key itself — only the db path.)
            LogKeyFailed(ex, connectionString);
            return null;
        }
    }

    private static UserRecord ToRecord(UserRow row) => new(
        row.Username,
        row.PasswordHash,
        row.Scopes,
        ParseStamp(row.CreatedUtc),
        string.IsNullOrEmpty(row.LastLoginUtc) ? null : ParseStamp(row.LastLoginUtc),
        Callsign: string.IsNullOrEmpty(row.Callsign) ? null : row.Callsign,
        TotpSecret: string.IsNullOrEmpty(row.TotpSecret) ? null : row.TotpSecret,
        LastTotpCounter: row.LastTotpCounter);

    private static string Stamp(DateTimeOffset value) => value.ToString("o", CultureInfo.InvariantCulture);

    private static DateTimeOffset ParseStamp(string value) =>
        DateTimeOffset.Parse(value, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind);

    private static bool TryFromBase64(string s, out byte[] bytes)
    {
        try
        {
            bytes = Convert.FromBase64String(s);
            return true;
        }
        catch (FormatException)
        {
            bytes = [];
            return false;
        }
    }

    // Dapper row DTO (mutable so Dapper's setter mapping binds it).
    private sealed class UserRow
    {
        public string Username { get; set; } = string.Empty;
        public string PasswordHash { get; set; } = string.Empty;
        public string Scopes { get; set; } = string.Empty;
        public string CreatedUtc { get; set; } = string.Empty;
        public string? LastLoginUtc { get; set; }
        public string? Callsign { get; set; }
        public string? TotpSecret { get; set; }
        public long? LastTotpCounter { get; set; }
    }

    [LoggerMessage(Level = LogLevel.Warning,
        Message = "User store: could not initialise the schema ({Db}); web auth is unavailable for this run.")]
    private partial void LogSchemaFailed(Exception ex, string db);

    [LoggerMessage(Level = LogLevel.Warning,
        Message = "User store: a read failed ({Db}); treating as empty/absent.")]
    private partial void LogReadFailed(Exception ex, string db);

    [LoggerMessage(Level = LogLevel.Warning,
        Message = "User store: a write failed ({Db}); the change was not persisted.")]
    private partial void LogWriteFailed(Exception ex, string db);

    [LoggerMessage(Level = LogLevel.Warning,
        Message = "User store: could not read or persist the JWT signing key ({Db}); web auth cannot be enabled.")]
    private partial void LogKeyFailed(Exception ex, string db);
}
