// Code generated by tools/Packet.Sdl.CodeGen from
// spec-sdl/data-link/disconnected.sdl.yaml. DO NOT EDIT. Run `dotnet run
// --project tools/Packet.Sdl.CodeGen` to regenerate.

#include "ax25sdl.h"
#include <stdio.h>
#include <string.h>

extern const StatePage data_link_disconnected;

#define ASSERT(cond, msg)                                                      \
  do {                                                                         \
    if (!(cond)) {                                                             \
      fprintf(stderr, "FAIL: %s\n", msg);                                      \
      return 1;                                                                \
    }                                                                          \
  } while (0)
#define ASSERT_STREQ(a, b, msg) ASSERT(strcmp((a), (b)) == 0, msg)

static int test_source_figure(void) {
  ASSERT_STREQ(data_link_disconnected.source.figure, "figc4.1",
               "source.figure");
  return 0;
}

static int test_transitions_count(void) {
  ASSERT(data_link_disconnected.transitions_len == 17, "transitions count");
  return 0;
}

static int test_t01_dl_disconnect_request(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t01_dl_disconnect_request") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t01_dl_disconnect_request not found");
  ASSERT_STREQ(t->on, "DL_DISCONNECT_request", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "DL_DISCONNECT_confirm", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[0].kind");
  return 0;
}

static int test_t02_dl_unit_data_request(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t02_dl_unit_data_request") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t02_dl_unit_data_request not found");
  ASSERT_STREQ(t->on, "DL_UNIT_DATA_request", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "UI_command", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[0].kind");
  return 0;
}

static int test_t03_dl_connect_request(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t03_dl_connect_request") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t03_dl_connect_request not found");
  ASSERT_STREQ(t->on, "DL_CONNECT_request", "on");
  ASSERT_STREQ(t->next, "AwaitingConnection", "next");
  ASSERT(t->actions_len == 4, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "SRT := Initial Default", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "T1V := 2 * SRT", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_PROCESSING, "actions[1].kind");
  ASSERT_STREQ(t->actions[2].verb, "Establish_Data_Link", "actions[2].verb");
  ASSERT(t->actions[2].kind == AX25SDL_KIND_SUBROUTINE, "actions[2].kind");
  ASSERT_STREQ(t->actions[3].verb, "set_layer_3_initiated", "actions[3].verb");
  ASSERT(t->actions[3].kind == AX25SDL_KIND_PROCESSING, "actions[3].kind");
  return 0;
}

static int test_t04_all_other_primitives_from_lower_layer(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t04_all_other_primitives_from_lower_layer") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t04_all_other_primitives_from_lower_layer not found");
  ASSERT_STREQ(t->on, "all_other_primitives__from_lower_layer", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 0, "actions count");
  return 0;
}

static int test_t05_all_other_commands(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t05_all_other_commands") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t05_all_other_commands not found");
  ASSERT_STREQ(t->on, "all_other_commands", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 2, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "F := P", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "DM", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[1].kind");
  return 0;
}

static int test_t06_all_other_primitives_from_upper_layer(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t06_all_other_primitives_from_upper_layer") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t06_all_other_primitives_from_upper_layer not found");
  ASSERT_STREQ(t->on, "all_other_primitives__from_upper_layer", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "discard_primitive", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  return 0;
}

static int test_t07_control_field_error(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t07_control_field_error") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t07_control_field_error not found");
  ASSERT_STREQ(t->on, "control_field_error", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "DL_ERROR_indication_L", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[0].kind");
  return 0;
}

static int test_t08_info_not_permitted_in_frame(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t08_info_not_permitted_in_frame") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t08_info_not_permitted_in_frame not found");
  ASSERT_STREQ(t->on, "info_not_permitted_in_frame", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "DL_ERROR_indication_M", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[0].kind");
  return 0;
}

static int test_t09_u_or_s_frame_length_error(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t09_u_or_s_frame_length_error") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t09_u_or_s_frame_length_error not found");
  ASSERT_STREQ(t->on, "u_or_s_frame_length_error", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "DL_ERROR_indication_N", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[0].kind");
  return 0;
}

static int test_t10_ua_received(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id, "t10_ua_received") ==
        0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t10_ua_received not found");
  ASSERT_STREQ(t->on, "UA_received", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "DL_ERROR_indication_C_D",
               "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[0].kind");
  return 0;
}

static int test_t11_ui_received_p_eq_1(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t11_ui_received_p_eq_1") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t11_ui_received_p_eq_1 not found");
  ASSERT_STREQ(t->on, "UI_received", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT_STREQ(t->guard, "P_eq_1", "guard");
  ASSERT(t->actions_len == 3, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "UI_Check", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SUBROUTINE, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "F := 1", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_PROCESSING, "actions[1].kind");
  ASSERT_STREQ(t->actions[2].verb, "DM", "actions[2].verb");
  ASSERT(t->actions[2].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[2].kind");
  return 0;
}

static int test_t12_ui_received_p_eq_0(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t12_ui_received_p_eq_0") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t12_ui_received_p_eq_0 not found");
  ASSERT_STREQ(t->on, "UI_received", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT_STREQ(t->guard, "not P_eq_1", "guard");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "UI_Check", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SUBROUTINE, "actions[0].kind");
  return 0;
}

static int test_t13_disc_received(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id, "t13_disc_received") ==
        0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t13_disc_received not found");
  ASSERT_STREQ(t->on, "DISC_received", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT(t->actions_len == 2, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "F := P", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "DM", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[1].kind");
  return 0;
}

static int test_t14_sabm_received_able(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t14_sabm_received_able") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t14_sabm_received_able not found");
  ASSERT_STREQ(t->on, "SABM_received", "on");
  ASSERT_STREQ(t->next, "Connected", "next");
  ASSERT_STREQ(t->guard, "able_to_establish", "guard");
  ASSERT(t->actions_len == 12, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "F := P", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "set_version_2_0", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_PROCESSING, "actions[1].kind");
  ASSERT_STREQ(t->actions[2].verb, "UA", "actions[2].verb");
  ASSERT(t->actions[2].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[2].kind");
  ASSERT_STREQ(t->actions[3].verb, "Clear_Exception_Conditions",
               "actions[3].verb");
  ASSERT(t->actions[3].kind == AX25SDL_KIND_SUBROUTINE, "actions[3].kind");
  ASSERT_STREQ(t->actions[4].verb, "V(s) := 0", "actions[4].verb");
  ASSERT(t->actions[4].kind == AX25SDL_KIND_PROCESSING, "actions[4].kind");
  ASSERT_STREQ(t->actions[5].verb, "V(a) := 0", "actions[5].verb");
  ASSERT(t->actions[5].kind == AX25SDL_KIND_PROCESSING, "actions[5].kind");
  ASSERT_STREQ(t->actions[6].verb, "V(r) := 0", "actions[6].verb");
  ASSERT(t->actions[6].kind == AX25SDL_KIND_PROCESSING, "actions[6].kind");
  ASSERT_STREQ(t->actions[7].verb, "DL_CONNECT_indication", "actions[7].verb");
  ASSERT(t->actions[7].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[7].kind");
  ASSERT_STREQ(t->actions[8].verb, "SRT := Initial Default", "actions[8].verb");
  ASSERT(t->actions[8].kind == AX25SDL_KIND_PROCESSING, "actions[8].kind");
  ASSERT_STREQ(t->actions[9].verb, "T1V := 2 * SRT", "actions[9].verb");
  ASSERT(t->actions[9].kind == AX25SDL_KIND_PROCESSING, "actions[9].kind");
  ASSERT_STREQ(t->actions[10].verb, "start_T3", "actions[10].verb");
  ASSERT(t->actions[10].kind == AX25SDL_KIND_PROCESSING, "actions[10].kind");
  ASSERT_STREQ(t->actions[11].verb, "RC := 0", "actions[11].verb");
  ASSERT(t->actions[11].kind == AX25SDL_KIND_PROCESSING, "actions[11].kind");
  return 0;
}

static int test_t15_sabm_received_unable(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t15_sabm_received_unable") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t15_sabm_received_unable not found");
  ASSERT_STREQ(t->on, "SABM_received", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT_STREQ(t->guard, "not able_to_establish", "guard");
  ASSERT(t->actions_len == 2, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "F := P", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "DM", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[1].kind");
  return 0;
}

static int test_t16_sabme_received_able(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t16_sabme_received_able") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t16_sabme_received_able not found");
  ASSERT_STREQ(t->on, "SABME_received", "on");
  ASSERT_STREQ(t->next, "Connected", "next");
  ASSERT_STREQ(t->guard, "able_to_establish", "guard");
  ASSERT(t->actions_len == 12, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "F := P", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "set_version_2_2", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_PROCESSING, "actions[1].kind");
  ASSERT_STREQ(t->actions[2].verb, "UA", "actions[2].verb");
  ASSERT(t->actions[2].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[2].kind");
  ASSERT_STREQ(t->actions[3].verb, "Clear_Exception_Conditions",
               "actions[3].verb");
  ASSERT(t->actions[3].kind == AX25SDL_KIND_SUBROUTINE, "actions[3].kind");
  ASSERT_STREQ(t->actions[4].verb, "V(s) := 0", "actions[4].verb");
  ASSERT(t->actions[4].kind == AX25SDL_KIND_PROCESSING, "actions[4].kind");
  ASSERT_STREQ(t->actions[5].verb, "V(a) := 0", "actions[5].verb");
  ASSERT(t->actions[5].kind == AX25SDL_KIND_PROCESSING, "actions[5].kind");
  ASSERT_STREQ(t->actions[6].verb, "V(r) := 0", "actions[6].verb");
  ASSERT(t->actions[6].kind == AX25SDL_KIND_PROCESSING, "actions[6].kind");
  ASSERT_STREQ(t->actions[7].verb, "DL_CONNECT_indication", "actions[7].verb");
  ASSERT(t->actions[7].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[7].kind");
  ASSERT_STREQ(t->actions[8].verb, "SRT := Initial Default", "actions[8].verb");
  ASSERT(t->actions[8].kind == AX25SDL_KIND_PROCESSING, "actions[8].kind");
  ASSERT_STREQ(t->actions[9].verb, "T1V := 2 * SRT", "actions[9].verb");
  ASSERT(t->actions[9].kind == AX25SDL_KIND_PROCESSING, "actions[9].kind");
  ASSERT_STREQ(t->actions[10].verb, "start_T3", "actions[10].verb");
  ASSERT(t->actions[10].kind == AX25SDL_KIND_PROCESSING, "actions[10].kind");
  ASSERT_STREQ(t->actions[11].verb, "RC := 0", "actions[11].verb");
  ASSERT(t->actions[11].kind == AX25SDL_KIND_PROCESSING, "actions[11].kind");
  return 0;
}

static int test_t17_sabme_received_unable(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < data_link_disconnected.transitions_len; i++) {
    if (strcmp(data_link_disconnected.transitions[i].id,
               "t17_sabme_received_unable") == 0) {
      t = &data_link_disconnected.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t17_sabme_received_unable not found");
  ASSERT_STREQ(t->on, "SABME_received", "on");
  ASSERT_STREQ(t->next, "Disconnected", "next");
  ASSERT_STREQ(t->guard, "not able_to_establish", "guard");
  ASSERT(t->actions_len == 2, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "F := P", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "DM", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[1].kind");
  return 0;
}

int main(void) {
  int rc = 0;
  rc |= test_source_figure();
  rc |= test_transitions_count();
  rc |= test_t01_dl_disconnect_request();
  rc |= test_t02_dl_unit_data_request();
  rc |= test_t03_dl_connect_request();
  rc |= test_t04_all_other_primitives_from_lower_layer();
  rc |= test_t05_all_other_commands();
  rc |= test_t06_all_other_primitives_from_upper_layer();
  rc |= test_t07_control_field_error();
  rc |= test_t08_info_not_permitted_in_frame();
  rc |= test_t09_u_or_s_frame_length_error();
  rc |= test_t10_ua_received();
  rc |= test_t11_ui_received_p_eq_1();
  rc |= test_t12_ui_received_p_eq_0();
  rc |= test_t13_disc_received();
  rc |= test_t14_sabm_received_able();
  rc |= test_t15_sabm_received_unable();
  rc |= test_t16_sabme_received_able();
  rc |= test_t17_sabme_received_unable();
  return rc;
}
